// Generated by gencpp from file ros_pkg/countRequest.msg
// DO NOT EDIT!


#ifndef ROS_PKG_MESSAGE_COUNTREQUEST_H
#define ROS_PKG_MESSAGE_COUNTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_pkg
{
template <class ContainerAllocator>
struct countRequest_
{
  typedef countRequest_<ContainerAllocator> Type;

  countRequest_()
    : x()  {
    }
  countRequest_(const ContainerAllocator& _alloc)
    : x(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _x_type;
  _x_type x;





  typedef boost::shared_ptr< ::ros_pkg::countRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_pkg::countRequest_<ContainerAllocator> const> ConstPtr;

}; // struct countRequest_

typedef ::ros_pkg::countRequest_<std::allocator<void> > countRequest;

typedef boost::shared_ptr< ::ros_pkg::countRequest > countRequestPtr;
typedef boost::shared_ptr< ::ros_pkg::countRequest const> countRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_pkg::countRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_pkg::countRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_pkg::countRequest_<ContainerAllocator1> & lhs, const ::ros_pkg::countRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_pkg::countRequest_<ContainerAllocator1> & lhs, const ::ros_pkg::countRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_pkg::countRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_pkg::countRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_pkg::countRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_pkg::countRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_pkg::countRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_pkg::countRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_pkg::countRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e90a477f371ee690ac763e15f14f34b";
  }

  static const char* value(const ::ros_pkg::countRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e90a477f371ee69ULL;
  static const uint64_t static_value2 = 0x0ac763e15f14f34bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_pkg::countRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_pkg/countRequest";
  }

  static const char* value(const ::ros_pkg::countRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_pkg::countRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string x\n"
"\n"
;
  }

  static const char* value(const ::ros_pkg::countRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_pkg::countRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct countRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_pkg::countRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_pkg::countRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_PKG_MESSAGE_COUNTREQUEST_H
