// Generated by gencpp from file ros_pkg/count.msg
// DO NOT EDIT!


#ifndef ROS_PKG_MESSAGE_COUNT_H
#define ROS_PKG_MESSAGE_COUNT_H

#include <ros/service_traits.h>


#include <ros_pkg/countRequest.h>
#include <ros_pkg/countResponse.h>


namespace ros_pkg
{

struct count
{

typedef countRequest Request;
typedef countResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct count
} // namespace ros_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_pkg::count > {
  static const char* value()
  {
    return "bfeef1b0057338fff2c60cd9004009fe";
  }

  static const char* value(const ::ros_pkg::count&) { return value(); }
};

template<>
struct DataType< ::ros_pkg::count > {
  static const char* value()
  {
    return "ros_pkg/count";
  }

  static const char* value(const ::ros_pkg::count&) { return value(); }
};


// service_traits::MD5Sum< ::ros_pkg::countRequest> should match
// service_traits::MD5Sum< ::ros_pkg::count >
template<>
struct MD5Sum< ::ros_pkg::countRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_pkg::count >::value();
  }
  static const char* value(const ::ros_pkg::countRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_pkg::countRequest> should match
// service_traits::DataType< ::ros_pkg::count >
template<>
struct DataType< ::ros_pkg::countRequest>
{
  static const char* value()
  {
    return DataType< ::ros_pkg::count >::value();
  }
  static const char* value(const ::ros_pkg::countRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_pkg::countResponse> should match
// service_traits::MD5Sum< ::ros_pkg::count >
template<>
struct MD5Sum< ::ros_pkg::countResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_pkg::count >::value();
  }
  static const char* value(const ::ros_pkg::countResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_pkg::countResponse> should match
// service_traits::DataType< ::ros_pkg::count >
template<>
struct DataType< ::ros_pkg::countResponse>
{
  static const char* value()
  {
    return DataType< ::ros_pkg::count >::value();
  }
  static const char* value(const ::ros_pkg::countResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_PKG_MESSAGE_COUNT_H
